apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotics-model
  labels:
    app: robotics-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: robotics-model
  template:
    metadata:
      labels:
        app: robotics-model
    spec:
      containers:
        - name: robotics-model
          image: ghcr.io/daeunkim-dev/robotics-model:latest  # 실제 빌드 시 교체
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_VERSION
              value: "v1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
