apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-dispatch-token
  namespace: robotics-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ?
    kind: ClusterSecretStore
  target:
    name: github-dispatch
  data:
    - secretKey: GH_TOKEN
      remoteRef:
        key: robotics/mlops
        property: GH_TOKEN
