apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: robotics-model-alerts
  namespace: ?
  labels: { release: prometheus }
spec:
  groups:
    - name: api-slo
      rules:
        - alert: HighLatencyP95
          expr: histogram_quantile(0.95, sum(rate(inference_duration_seconds_bucket[5m])) by (le)) > 0.5
          for: 10m
          labels: { severity: warning }
          annotations:
            summary: "p95 지연 상승"
            description: "지난 10분 p95 > 0.5s (튜닝: 서비스 SLO에 맞추어 조정)"
        - alert: HighErrorRate
          expr: sum(rate(inference_failure_total[5m])) / sum(rate(inference_requests_total[5m])) > 0.05
          for: 5m
          labels: { severity: critical }
          annotations:
            summary: "5xx/실패 비율 5% 초과"
            description: "지난 5분 실패율 > 5%"

    - name: model-quality
      rules:
        - alert: LowConfidenceSpike
          expr: (rate(inference_low_confidence_total[5m]) / rate(inference_requests_total[5m])) > 0.20
          for: 10m
          labels: { severity: warning }
          annotations:
            summary: "낮은 확신 비율 급증"
            description: "최근 10분간 low confidence > 20% (모델/데이터 이상 가능)"
        - alert: InputDriftDetected
          expr: avg_over_time(input_kl_divergence[15m]) > 0.1
          for: 15m
          labels: { severity: warning }
          annotations:
            summary: "입력 분포 드리프트 감지"
            description: "KL Divergence > 0.1 (베이스라인 대비 입력 분포 변형)"

    - name: robotics-domain
      rules:
        - alert: ControlLoopJitterHigh
          expr: histogram_quantile(0.95, sum(rate(control_loop_jitter_seconds_bucket[5m])) by (le)) > 0.02
          for: 10m
          labels: { severity: warning }
          annotations:
            summary: "제어 루프 지터 과다"
            description: "p95 제어 지터 > 20ms (제어 안정성 저하)"
        - alert: SafetyStopSpike
          expr: sum(rate(safety_stop_total[5m])) > 3
          for: 5m
          labels: { severity: critical }
          annotations:
            summary: "안전정지 이벤트 급증"
            description: "5분간 safety_stop_total > 3 (원인 확인 필요)"
        - alert: LocalizationLostHigh
          expr: avg_over_time(localization_lost_ratio[10m]) > 0.2
          for: 10m
          labels: { severity: warning }
          annotations:
            summary: "Localization Lost 비율 높음"
            description: "최근 10분 Lost > 20% (맵/조명/센서 이상 가능)"

- alert: HighRestarts
  expr: sum(increase(kube_pod_container_status_restarts_total{namespace="?"}[10m])) by (pod) > 3
  for: 10m
  labels: { severity: warning }
  annotations:
    summary: "파드 재시작 과다"
    description: "10분 내 3회 이상 재시작"

- alert: CrashLoopBackOff
  expr: sum(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace="?"}) > 0
  for: 5m
  labels: { severity: critical }
  annotations:
    summary: "CrashLoopBackOff 발생"
    description: "컨테이너 반복 충돌"


- alert: HPAAtMax
  expr: kube_horizontalpodautoscaler_status_current_replicas{namespace="?", horizontalpodautoscaler="robotics-model-hpa"} 
        >= kube_horizontalpodautoscaler_spec_max_replicas{namespace="?", horizontalpodautoscaler="robotics-model-hpa"}
  for: 10m
  labels: { severity: warning }
  annotations:
    summary: "HPA 최대치 도달"
    description: "부하 대비 리소스 부족 가능"

- alert: CPUThrottlingHigh
  expr: rate(container_cpu_cfs_throttled_seconds_total{pod=~"robotics-model-.*"}[5m]) 
        / rate(container_cpu_cfs_periods_total{pod=~"robotics-model-.*"}[5m]) > 0.2
  for: 10m
  labels: { severity: warning }
  annotations:
    summary: "CPU 스로틀링 20% 초과"
    description: "리소스 제한 상향 또는 최적화 필요"


- alert: DependencyDown
  expr: up{job=~"mlflow|minio|otel|prometheus"} == 0
  for: 2m
  labels: { severity: critical }
  annotations:
    summary: "의존 서비스 다운"
    description: "MLflow/MinIO/OTLP/Prom 중 장애"

- alert: Envoy5xxSpike
  expr: sum(rate(istio_requests_total{response_code=~"5..", reporter="destination", destination_workload="robotics-model"}[5m])) > 1
  for: 5m
  labels: { severity: warning }
  annotations:
    summary: "메시 5xx 급증"
    description: "mTLS/라웃팅/백엔드 점검"

- alert: CrashLoopBackOff
  expr: sum(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff",namespace="?"}) > 0
  for: 5m
  labels: { severity: critical }
  annotations: { summary: "CrashLoopBackOff", description: "컨테이너 반복 충돌" }

- alert: HighRestarts
  expr: sum(increase(kube_pod_container_status_restarts_total{namespace="?"}[10m])) by (pod) > 3
  for: 10m
  labels: { severity: warning }
  annotations: { summary: "파드 재시작 과다", description: "10분 내 3회 이상" }


- alert: HPAAtMax
  expr: kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler="robotics-model-hpa",namespace="?"}
        >= kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler="robotics-model-hpa",namespace="?"}
  for: 10m
  labels: { severity: warning }
  annotations: { summary: "HPA 최대치", description: "리소스 한계" }

- alert: CPUThrottlingHigh
  expr: rate(container_cpu_cfs_throttled_seconds_total{pod=~"robotics-model-.*"}[5m]) /
        rate(container_cpu_cfs_periods_total{pod=~"robotics-model-.*"}[5m]) > 0.2
  for: 10m
  labels: { severity: warning }
  annotations: { summary: "CPU 스로틀링 20%+", description: "리미트/튜닝 필요" }



- alert: DependencyDown
  expr: up{job=~"mlflow|minio|otel|prometheus"} == 0
  for: 2m
  labels: { severity: critical }
  annotations: { summary: "의존 서비스 다운", description: "엔드포인트 확인" }


- alert: Envoy5xxSpike
  expr: sum(rate(istio_requests_total{response_code=~"5..", destination_workload="robotics-model"}[5m])) > 1
  for: 5m
  labels: { severity: warning }
  annotations: { summary: "Istio 5xx 스파이크", description: "라우팅/mTLS/백엔드 점검" }
