name: SLSA provenance
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  security-events: write

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate provenance
        run: echo "Generating SLSA provenance..."
